### ISSUE TITLE
Version 1.8.11 Debian bulseyes

### ISSUE THREAD

**Issue by michel-thomas** [escalate/ansible-raspberry-msmtp#1]
New Debian version 11 (bulseyes) includes a `msmtp` upgrade to version 1.8.11 (Debian 10 buster has 1.8.3 by default).

This new version (since 1.8.8) allows to replace `From:` header with `set_from_header on` parameter.

Could you please include this parameter in config?

Many thanks

**Comment by escalate** [comment]
Hello @esprit-libre 

Thank you for the feedback.
This role is optimized for Raspberry Pi OS only.
The current Raspberry Pi OS version is based on Debian 10 (Buster).
See also https://en.wikipedia.org/wiki/Raspberry_Pi_OS
So I will not implement this suggestion for the time being.
As soon as Raspberry Pi OS changes to Debian 11 I will adapt the role.
Feel free to fork this repository and make the change yourself.

Best regards
Felix

**Comment by escalate** [comment]
Hello @esprit-libre,

I have updated the role to Debian Bullseye.
To use the set_from_header switch, just overwrite the msmtp_defaults variable.

Example:
```
msmtp_defaults:
  aliases: "/etc/aliases"
  auth: "on"
  syslog: "on"
  tls: "on"
  set_from_header: "on"
```

Best regards
Felix
